apiVersion: v1
clusters:
- cluster:
    certificate-authority: ca-dal10-sovrin-metasystem-gf.pem
    server: https://c2.us-south.containers.cloud.ibm.com:24271
  name: sovrin-metasystem-gf/boeee1qd0uhgsckare0g
contexts:
- context:
    cluster: sovrin-metasystem-gf/boeee1qd0uhgsckare0g
    namespace: default
    user: gisolfi@us.ibm.com/676e862169714ceb00ae252ca8ffaaad
  name: sovrin-metasystem-gf/boeee1qd0uhgsckare0g
current-context: sovrin-metasystem-gf/boeee1qd0uhgsckare0g
kind: Config
preferences: {}
users:
- name: gisolfi@us.ibm.com/676e862169714ceb00ae252ca8ffaaad
  user:
    auth-provider:
      config:
        client-id: kube
        client-secret: kube
        id-token: eyJraWQiOiIyMDE5MDcyNCIsImFsZyI6IlJTMjU2In0.eyJpYW1faWQiOiJJQk1pZC0xMDAwMDBRS0ZCIiwiaXNzIjoiaHR0cHM6Ly9pYW0uYmx1ZW1peC5uZXQvaWRlbnRpdHkiLCJzdWIiOiJnaXNvbGZpQHVzLmlibS5jb20iLCJhdWQiOiJrdWJlIiwiZ2l2ZW5fbmFtZSI6IkRhbmllbCIsImZhbWlseV9uYW1lIjoiR2lzb2xmaSIsIm5hbWUiOiJEYW5pZWwgR2lzb2xmaSIsImVtYWlsIjoiZ2lzb2xmaUB1cy5pYm0uY29tIiwiZXhwIjoxNTgwNTA1MTIwLCJzY29wZSI6ImlibSBvcGVuaWQgY29udGFpbmVycy1rdWJlcm5ldGVzIiwiaWF0IjoxNTgwNTAxNTIwLCJzdWJfNjc2ZTg2MjE2OTcxNGNlYjAwYWUyNTJjYThmZmFhYWQiOiJnaXNvbGZpQHVzLmlibS5jb20iLCJpYW1faWRfNjc2ZTg2MjE2OTcxNGNlYjAwYWUyNTJjYThmZmFhYWQiOiJJQk1pZC0xMDAwMDBRS0ZCIiwiZ3JvdXBzXzY3NmU4NjIxNjk3MTRjZWIwMGFlMjUyY2E4ZmZhYWFkIjpbIkVkaXQgY29tcGFueSBwcm9maWxlIiwiU2VhcmNoIGNhc2VzIiwiVmlldyBhY2NvdW50IHN1bW1hcnkiLCJVcGRhdGUgcGF5bWVudCBkZXRhaWxzIiwiUmV0cmlldmUgdXNlcnMiLCJHZXQgY29tcGxpYW5jZSByZXBvcnQiLCJJRGFhUyBLdWJlcm5ldGVzIiwiQWRkIGNhc2VzIGFuZCB2aWV3IG9yZGVycyIsIk9uZS10aW1lIHBheW1lbnRzIiwiTGltaXQgRVUgY2FzZSByZXN0cmljdGlvbiIsIkVkaXQgY2FzZXMiLCJWaWV3IGNhc2VzIl19.ZDkfXIYpc-LZWWn_2gne1KjejEyTkDT_3mscweSdnzX2RAC4ZVbcX0G6rquE1mqDCNE1FtVIcQXiPMZ8zanfmS0Q2aRmTr1cyAPZXgqgSOtr56uFcetSC0Shf3kGXrwoFn8XYLhVX7osXZrEVuNBui2YZS0OKAYbAddD-xQhZ9vRQAncOJV9AwdN4uq_hhgLxLDxFAxdNIK986LvhsZEdujdEe1Yap-IOeBHD7chtNJplc6ciY6-reKoivEC7-3kBPF4UnHicsS5jGYYkYxZlXg22TF4gTkuW0KC94MnQJfHQxqYnObF_zXLnlNXlWAlBlRZ2r2qxDeoAmXI_73dWw
        idp-issuer-url: https://iam.bluemix.net/identity
        refresh-token: OKA5S8SKhxsMW4O6xxQHtjVdR-oqE0ESCK-K6I6_VQfXW_aY4V1xRQJE7JicNpBRpUxigM3tCxFEinP2nt6JDCyD5os6TWTnc3RBnsK4eTOcaqTktlKEpvCzaIpUrw3qnTZZKy2Y5xu3vZ1WPqVDOWEyx2Ss7vMjLKGQq2sR8dhSAZ6_m12Hu-qvGUXIbzdp-GtezCf0WtlZnolgyhniXGJLkcTBnoCfxsmE1utDpy6kWgp3TOfetXZ8Olt2pTDKJuzd-fwec6Gu6owDGMWrEvnwDrHy20lsFIeKa0YGlCg3OK6-ECjgbf0im2mMurFQwHcZ0_JzMtleqw7XleS51Ff1bHkPyLyXL1oRgybTSal7cjNgbsZtCtUlNsV4QgZ1h7kqPBMZINxX-UObf7w7biep1Y-j0TN80_dQgkRX_ikXEOdhuDKBju1ZvRwePwbktLHIFE5fR_gCHFoBHnLgL0B9LpLiAXmaXJEHpVHC11UGVSgiVxP9I48uTCo1AlHGkJm_uwNAet47Lpd5x_V5uJtl_rxCz6Fq3bU9SwmVZXVVeEpVanrwLKUQwH6kIViTZXZJlp6QoY38MtbBY-mdcOUOxxGNXOPttL-cmLBWkGImvlug6X6lx-uFim1neKnbFXnJcHarAz2J4LQgTrfTrseNVV_UhPLNi__LgZviZsSkrK9Q12SU3-NK0xgirocbhs6T_J4lw1ndAPmeIYjAfbGobX9cgMqiJSBcsQo6vmXaW1Lqwgm132ceHnWcnp5l8BX5fXzSNBLxka2eYeXp_RbB-PakC5qIqlgTlodLPezFgRyrWKSxQXui9SGHa1aZFhfULMUdrmaDoiDOLyk4LgqS7ic-c97SStsf2G5gCfDMp3zgF1RqnA7yXwplwKu52FYtvjbHpnkFrgZN1kOKA1gLR75RPi4_UGHERvlVVVeNTN0KqdLQ0R7gC0fxUL8XEv8y15L-PUvZGLHX4xgXkKcD9FRbXWkk2ySX_g--7KqY9pRjwM0nQlHSJ_FX6ssHwFwEdO9K5V5D552oK3aKGGcEwa7GwYdEiqU-WXGF-BNE_7Exi5g1hZeksMEUkVjo5vg
      name: oidc
