apiVersion: v1
clusters:
- cluster:
    certificate-authority: ca-dal10-sovrin-metasystem-gf.pem
    server: https://c2.us-south.containers.cloud.ibm.com:24271
  name: sovrin-metasystem-gf/boeee1qd0uhgsckare0g
contexts:
- context:
    cluster: sovrin-metasystem-gf/boeee1qd0uhgsckare0g
    namespace: default
    user: gisolfi@us.ibm.com/676e862169714ceb00ae252ca8ffaaad
  name: sovrin-metasystem-gf/boeee1qd0uhgsckare0g
current-context: sovrin-metasystem-gf/boeee1qd0uhgsckare0g
kind: Config
preferences: {}
users:
- name: gisolfi@us.ibm.com/676e862169714ceb00ae252ca8ffaaad
  user:
    auth-provider:
      config:
        client-id: kube
        client-secret: kube
        id-token: eyJraWQiOiIyMDE5MDcyNCIsImFsZyI6IlJTMjU2In0.eyJpYW1faWQiOiJJQk1pZC0xMDAwMDBRS0ZCIiwiaXNzIjoiaHR0cHM6Ly9pYW0uYmx1ZW1peC5uZXQvaWRlbnRpdHkiLCJzdWIiOiJnaXNvbGZpQHVzLmlibS5jb20iLCJhdWQiOiJrdWJlIiwiZ2l2ZW5fbmFtZSI6IkRhbmllbCIsImZhbWlseV9uYW1lIjoiR2lzb2xmaSIsIm5hbWUiOiJEYW5pZWwgR2lzb2xmaSIsImVtYWlsIjoiZ2lzb2xmaUB1cy5pYm0uY29tIiwiZXhwIjoxNTgwNjY3MzA3LCJzY29wZSI6ImlibSBvcGVuaWQgY29udGFpbmVycy1rdWJlcm5ldGVzIiwiaWF0IjoxNTgwNjYzNzA3LCJzdWJfNjc2ZTg2MjE2OTcxNGNlYjAwYWUyNTJjYThmZmFhYWQiOiJnaXNvbGZpQHVzLmlibS5jb20iLCJpYW1faWRfNjc2ZTg2MjE2OTcxNGNlYjAwYWUyNTJjYThmZmFhYWQiOiJJQk1pZC0xMDAwMDBRS0ZCIiwiZ3JvdXBzXzY3NmU4NjIxNjk3MTRjZWIwMGFlMjUyY2E4ZmZhYWFkIjpbIkVkaXQgY29tcGFueSBwcm9maWxlIiwiU2VhcmNoIGNhc2VzIiwiVmlldyBhY2NvdW50IHN1bW1hcnkiLCJVcGRhdGUgcGF5bWVudCBkZXRhaWxzIiwiUmV0cmlldmUgdXNlcnMiLCJHZXQgY29tcGxpYW5jZSByZXBvcnQiLCJJRGFhUyBLdWJlcm5ldGVzIiwiQWRkIGNhc2VzIGFuZCB2aWV3IG9yZGVycyIsIk9uZS10aW1lIHBheW1lbnRzIiwiTGltaXQgRVUgY2FzZSByZXN0cmljdGlvbiIsIkVkaXQgY2FzZXMiLCJWaWV3IGNhc2VzIl19.VfhKokGhXEfg3emq_KuK3N5jGq1bsDzXz8ouMyPQ8jGBBgmqjyKwnFaZR6rW4yPQWXkjMz4QQ8V_O9lALLBo_TCVbuAhCZKdJdgqS08DMo7b2Bg6AGQQzt1ByhLFETCvL9DaWJPUpR0uldVpH1VkeAhJAeuFlY0rC2uZryOTxBKKZT-Jyuym1REPZFanvcxL1jZX2OBvU3RqRAWVD5M2OKp-q5udVREuoA3tmyYJCoXskRoBmIULXyRSag2fu2MvlPfuRang3Zl1Dyit-S5grSIwPG3nx_HrzuztZzjfMjc7Tx7sNBKTw56HRbG-JRyBDvT3cUQLvQ03pK_xdUU8sw
        idp-issuer-url: https://iam.bluemix.net/identity
        refresh-token: OKD9X1X-f3PqI6AUUuBBLB1V2DuYqRY9f86v20smFYEaZlnoajmJL_ffJSih9yAXnH2BWdoHPZ8-ki9Hi-CuFcL7iujLW9pm7sDS9bxgDR15YpPOsR-cCrigIh3x5LLg8LJt_PwkI-Nt9-_E5hy50Ly1bh1Go7PR1Bn05RNAXnyYcmbgdHc1VyfVAhsl7-XK9Y1pBbXONaY0hxbVGNzVGsRtWrRPikPy09jLEl2qJc4VJ-cNWPIjSoMeD8lVQiZH-3PCPlCuko2f52VbMP5BrnzIsOLnx1pN2sD-hPMs3UUw-0OTE9l9w4urgL85EykXhBdFgjdaovQ7OI_bSQdsMCep6fYh6oFSDLqAMiIC20MVqM2M2gz7Bcburod7SbQDZuEYA0PLLa8MYyz007wJKhN6QjKHGaBmcpilboSA1oZfeAAJBtKqE2VZfKVt_gJNUla-vyXyL4Xwl__cVGzZ2bdRxyO9g5sftaXQj81a7-p4wrazYNQQl3mcLRkDZxTRhtiK17Fbbq86BtLCPbZl7i_3ETTkK-7ym_1AWxKfhcOgkOaKW2RLsQ-0lU1i6eEELCCra6RWgeUz7anu9a1rlSz4esWED1ya8Rp_JaY_qvU20HUsf8JVL3Q8U4u9LQj5peuoBtIIFQRKY16mwhxqtQjzOKQTrS-Y3ezliy3bG78kzHkairH6Dnb69k7Yl08RaiLFzJnpL43InIO3Su6Zm4y5AnFB-saxZuFDpYjVZEC5DQjNkabHBXjBK8lgXvFAOIb5rdyIQtipnldBOgY844QYj3ZbjPbul6hPYE5JvDkV-C9Kobae3s-vYte5XgfJ59Pv6Wf4_gGSr0bQ7iFDa3zgf29YSE4FvhBT7AOiF1Rtm3upB9NDHeshG-ivZ3KWRLKDLnBfQbCLEcIy8457NBBAjnwXujnpNAzvQhOG5Hu8-JR3i_ekBx1H-98sKwe6KEKipIQNi71U6jDShPQXn_uG1oweLWN9OnxHB9jnCc4a5TNYLRVvOGgaUAgP_hsxehehFB2eund_wEj0fhi-hH60kcVXIg0SzctxQDzmqBWx-eGU1nr7qoT4PLd9YXvFaFE
      name: oidc
